name = "Warzone"
author = "_udur_"
version = "2.0.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "775a05ee322bdff46f6108912a2e68e5c1ea7a150ac4b9923886354492e52f1b"

[versions]
minecraft = "1.20.1"
forge = "47.4.23"
