name = "Warzone"
author = "_udur_"
version = "2.0.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15bbc3f2f9a4d606196588e40497d7d6de05e286cc52bc0c755b3e3f1c81122e"

[versions]
minecraft = "1.20.1"
forge = "47.4.23"
